# Generated by Django 2.0.3 on 2018-08-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('numberToppings', models.IntegerField()),
                ('type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='topping',
            new_name='numberToppings',
        ),
        migrations.AddField(
            model_name='orders',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Toppings'),
        ),
    ]
