# Generated by Django 2.0.3 on 2018-08-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180808_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='Regular', max_length=2),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='Regular', max_length=2),
        ),
    ]
