# Generated by Django 2.0.3 on 2018-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180811_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='regular', max_length=2),
        ),
    ]
