# Generated by Django 2.0.3 on 2018-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180808_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='numberToppings',
            field=models.CharField(choices=[('CHEESE', 'Cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('SPECIAL', 'Special')], default='CHEESE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='numberToppings',
            field=models.CharField(choices=[('CHEESE', 'Cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('SPECIAL', 'Special')], default='CHEESE', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='R', max_length=2),
        ),
    ]
