# Generated by Django 2.0.3 on 2018-08-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180808_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='numberToppings',
            new_name='number_toppings',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='numberToppings',
            new_name='number_toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'Small')], default='S', max_length=1),
        ),
    ]
