# Generated by Django 2.0.3 on 2018-08-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180811_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='Regular', max_length=10),
        ),
    ]
