# Generated by Django 2.0.3 on 2018-08-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180811_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='number_toppings',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('1 topping', '1 topping'), ('2 toppings', '2 toppings'), ('3 toppings', '3 toppings'), ('Special', 'Special')], default='Cheese', max_length=12),
        ),
    ]
