# Generated by Django 2.0.3 on 2018-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180811_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_toppings',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('1 Topping', '1 topping'), ('2 Toppings', '2 toppings'), ('3 Toppings', '3 toppings'), ('Special', 'Special')], default='Cheese', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='number_toppings',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('1 Topping', '1 topping'), ('2 Toppings', '2 toppings'), ('3 Toppings', '3 toppings'), ('Special', 'Special')], default='Cheese', max_length=12),
        ),
    ]
