# Generated by Django 2.0.3 on 2018-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180811_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_toppings', models.CharField(default='Cheese', max_length=10)),
                ('size', models.CharField(default='Small', max_length=10)),
                ('type', models.CharField(default='Regular', max_length=10)),
                ('user', models.CharField(default='none', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
    ]
